import os

import pytest
from alembic import command
from alembic.config import Config
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url


TEST_DATABASE_URL = os.getenv(
    "TEST_DATABASE_URL",
    "postgresql+psycopg://fridivo_test:test-only@localhost:5433/fridivo_test",
)
database_name = make_url(TEST_DATABASE_URL).database or ""
if not database_name.endswith("_test"):
    raise RuntimeError(
        "Refusing to run tests: TEST_DATABASE_URL must point to a database ending in '_test'"
    )

# Application configuration is fixed before importing the application modules.
os.environ["DATABASE_URL"] = TEST_DATABASE_URL
os.environ["JWT_SECRET_KEY"] = "pytest-secret-key-never-use-in-production"
os.environ["JWT_ALGORITHM"] = "HS256"
os.environ["ACCESS_TOKEN_EXPIRE_MINUTES"] = "30"

from app.db.session import engine  # noqa: E402
from app.main import app  # noqa: E402


@pytest.fixture(scope="session", autouse=True)
def migrated_test_database():
    bootstrap_engine = create_engine(TEST_DATABASE_URL)
    with bootstrap_engine.begin() as connection:
        connection.execute(
            text(
                "CREATE TABLE IF NOT EXISTS products "
                "(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "marker TEXT, code TEXT, product_name TEXT, brands TEXT, "
                "quantity TEXT, categories TEXT, countries TEXT, image_url TEXT, "
                "nutriscore_grade TEXT)"
            )
        )
        for column_definition in (
            "code TEXT",
            "product_name TEXT",
            "brands TEXT",
            "quantity TEXT",
            "categories TEXT",
            "countries TEXT",
            "image_url TEXT",
            "nutriscore_grade TEXT",
        ):
            connection.execute(
                text(f"ALTER TABLE products ADD COLUMN IF NOT EXISTS {column_definition}")
            )
        connection.execute(
            text("CREATE UNIQUE INDEX IF NOT EXISTS ix_products_test_code ON products (code)")
        )
        connection.execute(
            text(
                "INSERT INTO products (id, marker) VALUES (-1, 'must-survive') "
                "ON CONFLICT (id) DO UPDATE SET marker = EXCLUDED.marker"
            )
        )
        connection.execute(
            text(
                "INSERT INTO products "
                "(id, code, product_name, brands, quantity, categories, countries, image_url, nutriscore_grade, marker) "
                "VALUES "
                "(1, '0801234567890', 'Pasta integrale', 'Fridivo Test', '500 g', "
                " 'Pasta, Cereals', 'en:italy', 'https://images.test/pasta.jpg', 'a', 'fixture'), "
                "(2, '8001234567895', 'Salsa per pasta', 'Dispensa Test', '350 g', "
                " 'Sauces', 'France', NULL, 'b', 'fixture'), "
                "(3, '8001234567896', 'Acqua naturale', 'Fonte Test', '1.5 L', "
                " 'Beverages, Waters', 'Italia', NULL, 'a', 'fixture'), "
                "(4, '4001234567890', 'Dark chocolate', 'Europe Test', '100 g', "
                " 'Snacks, Chocolate', 'Germany', NULL, 'd', 'fixture'), "
                "(101, '9000000000101', 'Rankingyogurt', 'Exact Foreign', '125 g', "
                " 'Dairy', 'Germany', NULL, 'b', 'search-ranking-fixture'), "
                "(102, '9000000000102', 'Rankingyogurt bianco', 'Italian One', '125 g', "
                " 'Dairy', 'Italy', 'https://images.test/yogurt-1.jpg', 'a', 'search-ranking-fixture'), "
                "(103, '9000000000103', 'Rankingyogurt greco', 'Italian Two', '150 g', "
                " 'Dairy', 'en:italy', 'https://images.test/yogurt-2.jpg', 'a', 'search-ranking-fixture'), "
                "(104, '9000000000104', 'Rankingyogurt magro', 'Italian Three', '125 g', "
                " 'Dairy', 'it:italia', 'https://images.test/yogurt-3.jpg', 'a', 'search-ranking-fixture'), "
                "(105, '9000000000105', 'Rankingyogurt vaniglia', 'Italian Four', '125 g', "
                " 'Dairy', 'Francia, Italia', 'https://images.test/yogurt-4.jpg', 'a', 'search-ranking-fixture'), "
                "(106, '9000000000106', 'Rankingyogurt fragola', 'Foreign Complete', '125 g', "
                " 'Dairy', 'France', 'https://images.test/yogurt-5.jpg', 'a', 'search-ranking-fixture'), "
                "(107, '9000000000107', 'Dessert Rankingyogurt', 'Italian Dessert', '100 g', "
                " 'Desserts', 'Italy', NULL, 'c', 'search-ranking-fixture'), "
                "(108, '9000000000108', 'Dessert speciale Rankingyogurt', 'Foreign Dessert', '100 g', "
                " 'Desserts', 'Spain', NULL, 'c', 'search-ranking-fixture') "
                "ON CONFLICT (code) DO UPDATE SET "
                "product_name = EXCLUDED.product_name, brands = EXCLUDED.brands, "
                "quantity = EXCLUDED.quantity, categories = EXCLUDED.categories, "
                "countries = EXCLUDED.countries, "
                "image_url = EXCLUDED.image_url, nutriscore_grade = EXCLUDED.nutriscore_grade, "
                "marker = EXCLUDED.marker"
            )
        )

    alembic_config = Config("alembic.ini")
    command.upgrade(alembic_config, "head")
    yield
    bootstrap_engine.dispose()


@pytest.fixture(autouse=True)
def clean_managed_tables(migrated_test_database):
    with engine.begin() as connection:
        connection.execute(text("DELETE FROM shopping_list_items"))
        connection.execute(text("DELETE FROM consumption_events"))
        connection.execute(text("DELETE FROM inventory_items"))
        connection.execute(text("DELETE FROM household_members"))
        connection.execute(text("DELETE FROM households"))
        connection.execute(text("DELETE FROM users"))


@pytest.fixture
def client() -> TestClient:
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture
def registration_payload() -> dict[str, str]:
    return {
        "email": "mario@example.com",
        "password": "correct-horse-battery-staple",
        "first_name": "Mario",
        "language_code": "it",
        "country_code": "IT",
        "household_name": "Casa Rossi",
        "currency_code": "EUR",
        "timezone": "Europe/Rome",
    }
